// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace CalendarDemo
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public const int addSampleEvent = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int calAccountName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int calDisplayName = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int eventStartDate = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int eventTitle = 2131034115;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CalendarList = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CalListItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int EventList = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int EventListItem = 2130903043;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			private String()
			{
			}
		}
	}
}
