// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("XaminarAnimations.Resource", IsApplication=true)]

namespace XaminarAnimations
{
	
	
	public partial class Resource
	{
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int box = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int pic1 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int pic2 = 2130837507;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int animatedLayout = 2131034112;
			
			// aapt resource value: 0x7f05000a
			public const int counterText = 2131034122;
			
			// aapt resource value: 0x7f050001
			public const int firstLayout = 2131034113;
			
			// aapt resource value: 0x7f050005
			public const int frameLayout1 = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int karmaMeter = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int karmaSeeker = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int linearLayout1 = 2131034121;
			
			// aapt resource value: 0x7f050004
			public const int myButton = 2131034116;
			
			// aapt resource value: 0x7f05000b
			public const int pictureZone = 2131034123;
			
			// aapt resource value: 0x7f050002
			public const int secondLayout = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int switchButton = 2131034115;
			
			// aapt resource value: 0x7f050008
			public const int textView1 = 2131034120;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int LayoutAnimationLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int PropertyAnimationLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ViewAnimationLayout = 2130903043;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			private String()
			{
			}
		}
	}
}
